name: ENV Variables
on: pull_request
env:
  WF_EVN: Avaiable to all jobs


jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
     - name: Check out my other private repo
       uses: actions/checkout@v2
       with:
        repository: Williamgerraty/infra-test-automation
        token: ${{ secrets.test }}
     - name: list files
       run: |
          export SECRET_ACCESS_KEY=${{ secrets.key }}
          export ACCESS_KEY_ID=${{ secrets.id }}
          pip install -U pytest
          python -m pip install boto3
          pytest test_example.py

          
