name: ENV Variables
on: push
env:
  WF_EVN: Avaiable to all jobs


jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
     - name: Check out my other private repo
       uses: actions/checkout@master
       with:
        repository: Williamgerraty/infra-test-automation
        token: ${{ secrets.test }}